PROJECT_NAME: Yassar
PROJECT_ID: goqvhmgdefqpfmqusmlg
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: your_supabase_access_token
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcXZobWdkZWZxcGZtcXVzbWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MTE3NDAsImV4cCI6MjA1NTA4Nzc0MH0.A8Fsx15b5COywRps30GLc9ECB8XqinmOEnKA4PadEEA
SERVICE_KEY: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcXZobWdkZWZxcGZtcXVzbWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MTE3NDAsImV4cCI6MjA1NTA4Nzc0MH0.A8Fsx15b5COywRps30GLc9ECB8XqinmOEnKA4PadEEA

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH:
SUPABASE_PUBLIC_URL: https://goqvhmgdefqpfmqusmlg.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

SCHEDULE_STATUS: "off"

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR:
TRACE_COLLECTOR_ENDPOINT:

MAX_SERVER_REQUEST_BODY_SIZE: 8388608

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
